### ISSUE TITLE
Make clearer variable declarations

### ISSUE THREAD

**Issue by Paperzlel** [Pistonite/celer#149]
**Is your feature request related to a problem? Please describe.**
Currently variables seem to appear out of some mystic fog and don't have a clear way of being found or having their values re-assigned.

**Describe the solution you'd like**
Some form of preset syntax where we have a "vars" section that can be used to setup any we'd like to use. A way to specify what kind of variable they are would also be nice (like Java or C).

**Describe alternatives you've considered**
Making the "vars" keyword in plugins be able to specify a value, and allowing operators to be used such as += to increment variables

**Additional context**
I was trying to find the source of Pancake's issues with the counting for variables and stumbled onto this while doing so. The counter doesn't work at ALL, since it includes strings as well and we can't add to strings.

**Comment by Pistonight** [comment]
The BOTW presets clearly says it requires the `variables` plugin to work https://github.com/Pistonight/celer-presets/blob/main/botw/README.md#example

More details: https://celer.pistonite.org/docs/plugin/variables
